### ISSUE TITLE
Add course description

### ISSUE THREAD

**Issue by faroit** [faroit/reproducible-audio-research#1]
- [ ] what is the course about
- [ ] what is the take home message for students
- [ ] set the course rules, deliverables, what if paper reproduction fails
- [ ] link to @audiolabs course

**Comment by faroit** [comment]
@bmcfee can I copy content from your slides?

**Comment by bmcfee** [comment]
Yup -- the course materials are CC licensed.

**Comment by faroit** [comment]
this will be closed because we will move the seminar course organisation to a private repository until the students opted-in for making their results public
